# Generated by Django 3.2.9 on 2021-12-03 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_test',
            new_name='task_text',
        ),
    ]
